export const AssetUrls = {
  lava: 'assets/img/lava.jpg',
  platform1: 'assets/img/platform1.jpg',
  rock: 'assets/img/rock.png',
  flame: 'assets/img/spritesheets/flame.png',
  explosion: 'assets/img/spritesheets/explosion.png',
  debugPlayerSprite: {
    // img: 'assets/img/atlas/satlas-debug-player.png',
    // json: 'assets/img/atlas/satlas-debug-player.json',
    img: 'assets/img/spritesheets/ss-debug-player.png',
    imgRed: 'assets/img/spritesheets/ss-debug-player-red.png',
    imgBlue: 'assets/img/spritesheets/ss-debug-player-blue.png',
    imgGreen: 'assets/img/spritesheets/ss-debug-player-green.png',
    json: 'assets/img/spritesheets/ss-debug-player.json',
    chunkImg: 'assets/img/atlas/satlas-debug-sprite-chunk.png',
    chunkJson: 'assets/img/atlas/satlas-debug-sprite-chunk.json',
  },
  playerMikhail: {
    img: 'assets/img/atlas/satlas-mikhail.png',
    json: 'assets/img/atlas/satlas-mikhail.json',
    chunkImg: 'assets/img/atlas/satlas-mikhail-chunk.png',
    chunkJson: 'assets/img/atlas/satlas-mikhail-chunk.json',
  },
  playerAdriana: {
    img: 'assets/img/atlas/satlas-adriana.png',
    json: 'assets/img/atlas/satlas-adriana.json',
    chunkImg: 'assets/img/atlas/satlas-adriana-chunk.png',
    chunkJson: 'assets/img/atlas/satlas-adriana-chunk.json',
  },
  dragon: {
    img: 'assets/img/spritesheets/ss-dragon.png',
    imgRed: 'assets/img/spritesheets/ss-dragon-red.png',
    json: 'assets/img/spritesheets/ss-dragon.json',
    img800Red: 'assets/img/spritesheets/ss-dragon-800-red.png',
    json800: 'assets/img/spritesheets/ss-dragon-800.json',
  },
  meatSteaks: {
    img: 'assets/img/atlas/satlas-meat-steaks.png',
    json: 'assets/img/atlas/satlas-meat-steaks.json',
  },
};
